### ISSUE TITLE
Add Table of Content to CBZ file

### ISSUE THREAD

**Issue by xavierBizoux** [hyugogirubato/cbz#15]
Hi 
Thank you for the job done on this project. 
I have a question more than an issue. 
I would like to add a table of content to CBZ file and provide specific names to each page. 
Is there a better way than adding an image of the ToC at the beginning of the CBZ file?

**Comment by hyugogirubato** [comment]
To add an equivalent of "Table" for the pages I only see this field that could correspond (or "key"). Maybe watch with ComicRack how they do it.

https://github.com/hyugogirubato/cbz/blob/main/cbz/models.py#L131
