### ISSUE TITLE
CBZ are repacked according to zipfile order not filename order

### ISSUE THREAD

**Issue by That-Sasha** [hyugogirubato/cbz#16]
zipfile opens a zipfile in the order the files were added to the zip, not in alphabetical order. cbz packs files in the same order as given by zipfile and renames them all based on this order.

Generally, ereaders will open a cbz in alphabetical order so it's possible to open a .cbz file, do nothing to it and then repack it and end up with the comic in a different order.

One workaround would be to allow packing with the original filenames. Another would be to have a filename attribute in the PageInfo class that is always used for packing and allow the user to set this value as needed.

**Comment by That-Sasha** [comment]
See example here: https://stackoverflow.com/a/77207053

**Comment by hyugogirubato** [comment]
I just adapted what you told me. It is now possible to keep the original name of images when unpacking (loading an existing cbz) or creating a cbz by using the `rename=False` argument when calling the function pack.

Can you confirm that this corresponds to the desired behavior?

Commit: https://github.com/hyugogirubato/cbz/commit/72c14449fcd53021ab2a86290c7f9682ba21ff9e https://github.com/hyugogirubato/cbz/commit/27a313fe4cf7d0e43b68ec0ced37a774abae5883

**Comment by That-Sasha** [comment]
LGTM, cheers!
Closing the issue

**Comment by hyugogirubato** [comment]
Ok great! I do a code review and publish the update on pip !
